# Generated by Django 5.1.5 on 2025-02-15 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photographer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_photographers', models.IntegerField(default=0)),
                ('total_clients', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_portfolios', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Platform Statistics',
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('portfolio_approval', 'Portfolio Approval Request'), ('user_report', 'User Report'), ('system_alert', 'System Alert')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('inquiries', models.IntegerField(default=0)),
                ('bookings', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='photographer.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Analytics',
                'unique_together': {('portfolio', 'date')},
            },
        ),
    ]
