# Generated by Django 5.1.6 on 2025-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_portfolio_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioanalytics',
            name='date',
            field=models.DateField(),
        ),
    ]
