# Generated by Django 5.1.6 on 2025-02-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='specialization',
            field=models.CharField(choices=[('portrait', 'Portrait Photography'), ('wedding', 'Wedding Photography'), ('landscape', 'Landscape Photography'), ('fashion', 'Fashion Photography'), ('wildlife', 'Wildlife Photography')], max_length=20),
        ),
    ]
