# Generated by Django 5.1.6 on 2025-02-16 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0002_alter_portfolio_specialization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='photographer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_portfolio', to=settings.AUTH_USER_MODEL),
        ),
    ]
